import Link from 'next/link';

export default function TermsPage() {
  return (
    <div style={{ background: '#F5F6FA', minHeight: '100vh' }}>
      <nav style={{ background: '#0B1437', padding: '16px 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <Link href="/" style={{ textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div style={{ width: '32px', height: '32px', background: 'linear-gradient(135deg, #C9A84C, #DFC06E)', borderRadius: '9px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '16px', fontWeight: 900, color: '#0B1437' }}>P</div>
          <span style={{ color: 'white', fontWeight: 800, fontSize: '18px' }}>PropCopy <span style={{ color: '#C9A84C' }}>AI</span></span>
        </Link>
        <Link href="/" style={{ color: '#C9A84C', textDecoration: 'none', fontWeight: 600, fontSize: '14px' }}>← Back to Home</Link>
      </nav>

      <div style={{ maxWidth: '760px', margin: '0 auto', padding: '60px 24px' }}>
        <h1 style={{ fontSize: '40px', fontWeight: 900, color: '#0B1437', letterSpacing: '-0.03em', marginBottom: '8px' }}>Terms of Service</h1>
        <p style={{ color: '#8892A4', fontSize: '15px', marginBottom: '48px' }}>Last updated: March 1, 2025</p>

        {[
          { title: '1. Acceptance of Terms', content: 'By accessing and using PropCopy AI, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this service.' },
          { title: '2. Description of Service', content: 'PropCopy AI provides an AI-powered content generation platform for real estate professionals. Our service generates listing descriptions, social media posts, buyer follow-up emails, and other real estate marketing content using artificial intelligence.' },
          { title: '3. User Responsibilities', content: 'You are responsible for reviewing all AI-generated content before use. While PropCopy AI strives to create accurate, compliant content, you must ensure all content complies with applicable laws, MLS rules, and fair housing regulations before publishing or submitting. You agree not to use our service for any unlawful purpose.' },
          { title: '4. Fair Housing Compliance', content: 'PropCopy AI is designed to avoid fair housing violations. However, you bear ultimate responsibility for ensuring your listings comply with the Fair Housing Act and all applicable state and local fair housing laws. Do not add content that discriminates based on race, color, national origin, religion, sex, familial status, or disability.' },
          { title: '5. Subscription and Payment', content: 'Paid subscriptions are billed monthly or annually in advance. All subscriptions include a 7-day free trial. After the trial period, you will be charged according to your selected plan. You may cancel at any time; cancellations take effect at the end of the current billing period.' },
          { title: '6. Intellectual Property', content: 'Content generated by PropCopy AI is licensed to you for use in your real estate business. You own the right to use, modify, and publish this content. PropCopy AI retains rights to the underlying models and platform.' },
          { title: '7. Limitation of Liability', content: 'PropCopy AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use or inability to use the service. Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim.' },
          { title: '8. Contact', content: 'Questions about these Terms? Contact us at legal@propcopyai.com.' },
        ].map((section) => (
          <div key={section.title} style={{ marginBottom: '36px' }}>
            <h2 style={{ fontSize: '20px', fontWeight: 800, color: '#0B1437', marginBottom: '12px' }}>{section.title}</h2>
            <p style={{ color: '#374151', fontSize: '16px', lineHeight: 1.8 }}>{section.content}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
